### ISSUE TITLE
Get V4R object recognition pipeline working and trained with example objects

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_launch#1]
from https://github.com/strands-project/v4r_ros_wrappers
 
installed from binary packages: `ros-indigo-v4r-ros-wrapper`

**Comment by marc-hanheide** [comment]
and to be tested on Pepper to see if it works. If not consider using [`rosbridge`](http://wiki.ros.org/rosbridge_suite) to make it a webservice, just like https://github.com/LCAS/ros_web_apis

**Comment by marc-hanheide** [comment]
@mtlazaro or @iocchi would it be possible to also get a data set for object training? @pet1330 can advise what exactly will be needed.

**Comment by mtlazaro** [comment]
Sure, we plan to do it next week. Let us know in advance what is needed.
