### ISSUE TITLE
write task controller for agreed tasks

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_launch#4]

**Comment by marc-hanheide** [comment]
see https://docs.google.com/document/d/1hbKG8kDjDA8ulWavLRsRMJMjw0T4TgYOE_0dg1rUWzw/edit for the tasks

**Comment by iocchi** [comment]
General idea is to define plans (file ``.plan`` in https://github.com/LCAS/spqrel_tools/tree/master/plans) 
Generate the PNP plan from plan files (``./gen_plan.sh <plan> <er>``)
Upload ``.pnml`` files on Pepper (``plans`` folder)
Implement actions and upload them in ``action`` folder.
Launch ``pnp_naoqi`` on Pepper (``bin`` folder)
Run a plan (e.g., ``./run_plan.sh <plan_name>`` )

**Comment by iocchi** [comment]
``cocktail_party.plan`` is under development and testing
