### ISSUE TITLE
test person detection and tracking with data sets

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/spqrel_launch#5]
Here are some datasets kindly provided by @mtlazaro: https://drive.google.com/drive/folders/0BwxxLhMGJyH9QkJWdk1SckQ2dzQ?usp=sharing

She said:
> Today we have partially acquired DATASET 1. 
> I've put the dataset in this shared folder.
> https://drive.google.com/drive/folders/0BwxxLhMGJyH9QkJWdk1SckQ2dzQ?usp=sharing
> 
> We use a coding explained in the doc and in the Readme of the folder to summarize state of the robot and of the person.
> 
> Let us know what you manage to do with the data or if you have any comment about this or future acquisitions.

**Comment by ALIYoussef** [comment]
I am trying to run the software we used in leòn on the new dataset  It will be fine if we collaborate on it.

**Comment by marc-hanheide** [comment]
@ALIYoussef that's good. Have you got the launch file you used anywhere? Do you want to put this in this repo?
